java:
  - oraclejdk8
os:
  - ubuntu/trusty64/m3.large
cassandra:
  - '2.1'
  - '2.2'
  - '3.0'
  - '3.11'
build:
  - script: |
      git clone --depth 1 https://github.com/datastax/native-protocol.git -b java1761
      pushd native-protocol
      mvn install -Dmaven.javadoc.skip=true -B -V
      popd
      rm -rf native-protocol
      git clone --depth 1 https://github.com/datastax/java-driver-shaded-guava.git -b java1761
      pushd java-driver-shaded-guava
      mvn install -Dmaven.javadoc.skip=true -B -V
      popd
      rm -rf java-driver-shaded-guava
  - type: maven
    version: 3.2.5
    goals: verify
    properties: |
      ccm.version=$CCM_CASSANDRA_VERSION
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml"
  - jacoco: true
disable_commit_status: true
